name: Biome

on:
  # Trigger the workflow on push or pull request to the main branch.
  pull_request:
    branches:
      - main

jobs:
  biome-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run Biome Linter
        run: npm run format-check
